apiVersion: v1
kind: Secret
metadata:
  name: mailu-admin-credentials
  labels:
    app: {{ include "mailu.fullname" . }}
    component: admin
data:
  password: {{ include "mailu.initialAccount.password" . }}
  username: {{ required "initialAccount.username" .Values.initialAccount.username | b64enc }}
type: Opaque
