# The secret key is required for protecting authentication cookies and must be set individually for each deployment
apiVersion: v1
kind: Secret
metadata:
  name: mailu-session-encryption-key
  labels:
    app: {{ include "mailu.fullname" . }}
data:
  key: {{ include "mailu.sessionEncryptionKey" . }}
type: Opaque
